#!/bin/zsh

# Create an array of routes
routes=(
  "avatar"
  "badge"
  "book"
  "button"
  "calendar"
  "checkbox"
  "choicebox"
  "code-block"
  "collapse"
  "combobox"
  "context-menu"
  "description"
  "drawer"
  "empty-state"
  "error"
  "feedback"
  "gauge"
  "grid"
  "input"
  "keyboard-input"
  "loading-dots"
  "menu"
  "modal"
  "note"
  "pagination"
  "progress"
  "radio"
  "scroller"
  "select"
  "show-more"
  "skeleton"
  "snippet"
  "spinner"
  "stack"
  "status-dot"
  "switch"
  "table"
  "tabs"
  "text"
  "textarea"
  "theme-switcher"
  "toast"
  "toggle"
  "tooltip"
  "window"
)

# Loop through the routes and create the files
for route in "${routes[@]}"
do
  mkdir -p "$route"
  touch "$route/+page.svelte"
  echo "<h1>"$route"</h1>" > "$route/+page.svelte"
  echo "Created $route/+page.svelte"
done

echo "All route files have been created."